/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/AccountForm.vue')['default']
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
  }
}
